FROM node:20-alpine
WORKDIR /app

ARG ENV
ARG DATABASE_URL
ARG JWT_SECRET
ARG CSRF_SECRET

ENV ENV=$ENV
ENV DATABASE_URL=$DATABASE_URL
ENV JWT_SECRET=$JWT_SECRET
ENV CSRF_SECRET=$CSRF_SECRET

COPY . .
RUN npm i
RUN npm run build
CMD ["npm", "run", "start"]
EXPOSE 3000